---
title: "writing_functions"
author: "Shina Min"
date: "2023-11-11"
output: github_document
---

```{r, include=FALSE}
library(tidyverse)
library(rvest)
```

## Do soemthing simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-scores

```{r}
z_scores = function(x) {
  
  if(!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if(length(x) < 3) {
    stop("Input must have a least three numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  z
  
}

z_scores(x_vec)
```


Try my function on some other things. These should give errors

```{r, error = TRUE}
z_scores(3)
z_scores("my name is Shina")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, TRUE))
```



## Multiple outputs

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, 
       sd = sd_x)
}
```


check that the function works.

```{r}
x_vec = rnorm(100, mean = 3, sd = 4)
mean_and_sd(x_vec)
```

## Multiple inputs

I'd like to do this with a function
```{r}
sim_data = tibble(
  x = rnorm(n = 100, mean = 2, sd = 3)
)

sim_data %>%
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

```


```{r}
sim_mean_sd = function(samp_size, mu = 3, sigma = 4) {
  
  sim_data = 
   tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma)
)

sim_data %>%
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
}

sim_mean_sd(samp_size = 100, mu = 6, sigma = 3)

sim_mean_sd(samp_size = 100)
```


## Let's review Napoleon Dynamite

```{r}
fellowship_ring = readxl::read_excel("./LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") |> 
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything())
```


```{r}

```





